import { z } from "zod"

export const questionnaireSchema = z.object({
  techSectors: z.array(z.string()).min(1, "Please select at least one tech sector"),
  roleTypes: z.array(z.string()).min(1, "Please select at least one role type"),
  workEnvironment: z.array(z.string()).min(1, "Please select at least one work environment"),
  companySize: z.array(z.string()).min(1, "Please select at least one company size"),
  experienceLevel: z.array(z.string()).min(1, "Please select at least one experience level"),
  workSchedule: z.array(z.string()).min(1, "Please select at least one work schedule"),
  technicalSkills: z.array(z.string()).min(1, "Please select at least one technical skill"),
  location: z.array(z.string()).min(1, "Please select at least one location preference"),
  salaryExpectations: z.array(z.string()).min(1, "Please select at least one salary expectation"),
})

export type QuestionnaireData = z.infer<typeof questionnaireSchema>

export const questionnaireOptions = {
  techSectors: [
    "Artificial Intelligence / Machine Learning",
    "Cloud Computing",
    "Cybersecurity",
    "Data Science / Analytics",
    "DevOps / Infrastructure",
    "E-commerce",
    "FinTech",
    "HealthTech",
    "Mobile Development",
    "Web Development",
    "Gaming",
    "IoT (Internet of Things)",
    "Blockchain / Crypto",
    "EdTech",
  ],
  roleTypes: [
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer",
    "DevOps Engineer",
    "Data Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Security Engineer",
    "QA / Test Engineer",
    "Product Manager",
    "Engineering Manager",
    "Solutions Architect",
    "UI/UX Designer",
  ],
  workEnvironment: ["Fully Remote", "Hybrid (2-3 days in office)", "Mostly In-Office", "Flexible / Your Choice"],
  companySize: [
    "Startup (1-50 employees)",
    "Small (51-200 employees)",
    "Medium (201-1000 employees)",
    "Large (1001-5000 employees)",
    "Enterprise (5000+ employees)",
  ],
  experienceLevel: [
    "Entry Level (0-2 years)",
    "Mid Level (3-5 years)",
    "Senior (6-10 years)",
    "Lead / Principal (10+ years)",
    "Executive / C-Level",
  ],
  workSchedule: ["Standard 9-5", "Flexible Hours", "Compressed Work Week", "Part-Time", "Contract / Freelance"],
  technicalSkills: [
    "JavaScript / TypeScript",
    "Python",
    "Java",
    "C# / .NET",
    "Go",
    "Rust",
    "React / Next.js",
    "Vue / Nuxt",
    "Angular",
    "Node.js",
    "Django / Flask",
    "Spring Boot",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker / Kubernetes",
    "PostgreSQL / MySQL",
    "MongoDB",
    "Redis",
    "GraphQL",
  ],
  location: [
    "United States",
    "Canada",
    "United Kingdom",
    "Europe",
    "Asia Pacific",
    "Latin America",
    "Remote (Anywhere)",
  ],
  salaryExpectations: ["$50k - $75k", "$75k - $100k", "$100k - $150k", "$150k - $200k", "$200k - $300k", "$300k+"],
}
